=== Flagbit/catalog/schema/catalog.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://lizardsandpumpkins.com"
        xmlns="http://lizardsandpumpkins.com"
        elementFormDefault="qualified">
    <xs:element name="catalog">
        <xs:complexType>
            <xs:all>
                <xs:element name="products" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="product" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="abstractProduct">
                                            <xs:sequence>
                                                <xs:element name="associated_products" minOccurs="0">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="product" type="abstractProduct"
                                                                    maxOccurs="unbounded"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="variations">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="attribute" type="xs:string"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                            <xs:attribute name="type" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="simple"/>
                                                        <xs:enumeration value="configurable"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                            <!-- The line below will most likely fail. Need XSD 1.1 parser to test. -->
                                            <xs:assert test="if(@type eq 'configurable') then associated_products
                                     else not(associated_products)"/>
                                        </xs:extension>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="listings" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="listing">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="criteria" type="criteria" maxOccurs="1"/>
                                    </xs:sequence>
                                    <xs:attribute name="url_key" type="xs:string" use="required"/>
                                    <xs:anyAttribute processContents="skip"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="abstractProduct">
        <xs:all>
            <xs:element name="images">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="image">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="file">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="xs:string">
                                                    <xs:anyAttribute processContents="skip"/>
                                                </xs:extension>
                                            </xs:simpleContent>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="label">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="xs:string">
                                                    <xs:anyAttribute processContents="skip"/>
                                                </xs:extension>
                                            </xs:simpleContent>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="attributes">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="attribute" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="name" type="xs:string" use="required"/>
                                <xs:anyAttribute processContents="skip"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="sku" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="tax_class" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="criteria">
        <xs:sequence>
            <xs:element name="attribute" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="name" type="xs:string" use="required"/>
                            <xs:attribute name="is" use="required">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Anything"/>
                                        <xs:enumeration value="Equal"/>
                                        <xs:enumeration value="GreaterOrEqualThan"/>
                                        <xs:enumeration value="GreaterThan"/>
                                        <xs:enumeration value="LessOrEqualThan"/>
                                        <xs:enumeration value="LessThan"/>
                                        <xs:enumeration value="Like"/>
                                        <xs:enumeration value="NotEqual"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="criteria" type="criteria" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="and"/>
                    <xs:enumeration value="or"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== Flagbit/catalog/tests/shared-fixture/simple_product_armflasher-v2.xml
<?xml version="1.0"?>
<catalog xmlns="http://lizardsandpumpkins.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://lizardsandpumpkins.com ../../schema/catalog.xsd">
    <products>
        <product type="simple" sku="118235-251" tax_class="19%">
            <images>
                <image>
                    <file>2013_pro_touch_118235-251.jpg</file>
                    <label>The main image label</label>
                </image>
                <image>
                    <file>2013_pro_touch_118235-251.jpg</file>
                    <label locale="de_DE">Der Text zum zweiten Bild</label>
                    <label locale="en_US">A secondary image label</label>
                </image>
            </images>
            <attributes>
                <attribute name="category" website="ru" locale="de_DE">sale</attribute>
                <attribute name="category" website="ru" locale="de_DE">men</attribute>
                <attribute name="category" website="ru" locale="de_DE">women</attribute>
                <attribute name="category" website="ru" locale="de_DE">women-accessories</attribute>
                <attribute name="category" website="ru" locale="en_US">sale</attribute>
                <attribute name="category" website="ru" locale="en_US">women-accessories</attribute>
                <attribute name="category" website="fr" locale="fr_FR">sale</attribute>
                <attribute name="non_canonical_url_key" website="ru" locale="de_DE">sale/led-arm-signallampe</attribute>
                <attribute name="non_canonical_url_key" website="ru" locale="de_DE">men/led-arm-signallampe</attribute>
                <attribute name="non_canonical_url_key" website="ru" locale="de_DE">women/led-arm-signallampe</attribute>
                <attribute name="non_canonical_url_key" website="ru" locale="de_DE">women-accessories/led-arm-signallampe</attribute>
                <attribute name="non_canonical_url_key" website="ru" locale="en_US">women/led-armflasher</attribute>
                <attribute name="non_canonical_url_key" website="ru" locale="en_US">women-accessories/led-armflasher</attribute>
                <attribute name="non_canonical_url_key" website="fr" locale="fr_FR">sale/armer-conduit</attribute>
                <attribute name="stock_qty">5</attribute>
                <attribute name="backorders">true</attribute>
                <attribute name="url_key" locale="de_DE">led-arm-signallampe</attribute>
                <attribute name="url_key" locale="en_US">led-armflasher</attribute>
                <attribute name="url_key" locale="fr_FR">armer-conduit</attribute>
                <attribute name="name" locale="de_DE">LED Arm-Signallampe (2)</attribute>
                <attribute name="name" locale="en_US">LED Armflasher (2)</attribute>
                <attribute name="name" locale="fr_FR">Armer Conduit (2)</attribute>
                <attribute name="price" website="ru">1.45</attribute>
                <attribute name="price" website="fr">22.22</attribute>
                <attribute name="special_price" website="ru">0.95</attribute>
                <attribute name="weight">11.2</attribute>
                <attribute name="description" locale="de_DE"><![CDATA[LED Arm-Signallampe<br />
<br />
LED Arm-Signallampe mit elastischem Band und Flasher mit variabler Blinkfolge,
Flasher abnehmbar.]]></attribute>
                <attribute name="description" locale="en_US"><![CDATA[Pro Touch LED Armflasher<br />
<br />
LED Armflasher with elastic Band and Flasher]]></attribute>
                <attribute name="brand">Pro Touch</attribute>
                <attribute name="style">Leuchten</attribute>
                <attribute name="gender">Damen</attribute>
                <attribute name="gender">Herren</attribute>
                <attribute name="color">d90000</attribute>
                <attribute name="color">000000</attribute>
            </attributes>
        </product>
    </products>
</catalog>

=== Flagbit/catalog/tests/shared-fixture/product_listings.xml
<?xml version="1.0"?>
<catalog xmlns="http://lizardsandpumpkins.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://lizardsandpumpkins.com ../../schema/catalog.xsd">
    <listings>
        <listing url_key="adidas-sale" website="ru" locale="de_DE">
            <criteria type="and">
                <attribute name="stock_qty" is="GreaterThan">0</attribute>
                <attribute name="category" is="Equal">sale</attribute>
                <attribute name="brand" is="Equal">Adidas</attribute>
            </criteria>
            <attributes>
                <attribute name="meta_title">Adidas Rausverkauf!</attribute>
                <attribute name="meta_description">Adidas Rausverkauf! Greifen Sie jetzt zu!</attribute>
            </attributes>
        </listing>
        <listing url_key="sale" website="ru" locale="de_DE">
            <criteria type="and">
                <attribute name="stock_qty" is="GreaterThan">0</attribute>
                <attribute name="category" is="Equal">sale</attribute>
            </criteria>
            <attributes>
                <attribute name="title">Sale</attribute>
                <attribute name="description">Special Offers!!</attribute>
                <attribute name="meta_description">Besondere Angebote!!</attribute>
            </attributes>
        </listing>
        <listing url_key="sale" website="fr" locale="fr_FR">
            <criteria type="and">
                <attribute name="stock_qty" is="GreaterThan">0</attribute>
                <attribute name="category" is="Equal">sale</attribute>
            </criteria>
            <attributes>
                <attribute name="meta_title">Vendre</attribute>
                <attribute name="meta_description">Acheter des chaussures de sport moins chères ? C’est possible grâce à
                    nos offres à prix discount. Commandez très simplement vos futures chaussures de course qui vous
                    seront expédiées rapidement.
                </attribute>
                <attribute name="meta_keywords">vendre, offre, proposition</attribute>
            </attributes>
        </listing>
        <listing url_key="asics" website="fr" locale="fr_FR">
            <criteria type="and">
                <attribute name="stock_qty" is="GreaterThan">0</attribute>
                <attribute name="brand" is="Equal">Asics</attribute>
            </criteria>
        </listing>
    </listings>
</catalog>

=== Flagbit/catalog/tests/shared-fixture/simple_product_adilette.xml
<?xml version="1.0"?>
<catalog xmlns="http://lizardsandpumpkins.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://lizardsandpumpkins.com ../../schema/catalog.xsd">
    <products>
        <product type="simple" sku="288193NEU" tax_class="19%">
            <images>
                <image>
                    <file>288193_14.jpg</file>
                    <label/>
                </image>
            </images>
            <attributes>
                <attribute name="url_key">adilette</attribute>
                <attribute name="name">Adilette</attribute>
                <attribute name="category">sale</attribute>
                <attribute name="price">14.92</attribute>
                <attribute name="brand">Adidas</attribute>
                <attribute name="gender">Herren</attribute>
                <attribute name="stock_qty">1</attribute>
                <attribute name="backorders">false</attribute>
                <attribute name="color">d90000</attribute>
                <attribute name="series">Adilette</attribute>
                <attribute name="news_from_date">2015-02-25 00:00:00</attribute>
            </attributes>
        </product>
    </products>
    
    
    <listings>
        <listing url_key="adidas-sale" website="ru" locale="de_DE">
            <criteria type="and">
                <attribute name="stock_qty" is="GreaterThan">0</attribute>
                <attribute name="category" is="Equal">sale</attribute>
                <attribute name="brand" is="Equal">Adidas</attribute>
            </criteria>
            <attributes>
                <attribute name="meta_title">Adidas Rausverkauf!</attribute>
                <attribute name="meta_description">Adidas Rausverkauf! Greifen Sie jetzt zu!</attribute>
            </attributes>
        </listing>
        <listing url_key="sale" website="ru" locale="de_DE">
            <criteria type="and">
                <attribute name="stock_qty" is="GreaterThan">0</attribute>
                <attribute name="category" is="Equal">sale</attribute>
            </criteria>
            <attributes>
                <attribute name="title">Sale</attribute>
                <attribute name="description">Special Offers!!</attribute>
                <attribute name="meta_description">Besondere Angebote!!</attribute>
            </attributes>
        </listing>
        <listing url_key="sale" website="fr" locale="fr_FR">
            <criteria type="and">
                <attribute name="stock_qty" is="GreaterThan">0</attribute>
                <attribute name="category" is="Equal">sale</attribute>
            </criteria>
            <attributes>
                <attribute name="meta_title">Vendre</attribute>
                <attribute name="meta_description">Acheter des chaussures de sport moins chères ? C’est possible grâce à
                    nos offres à prix discount. Commandez très simplement vos futures chaussures de course qui vous
                    seront expédiées rapidement.
                </attribute>
                <attribute name="meta_keywords">vendre, offre, proposition</attribute>
            </attributes>
        </listing>
        <listing url_key="asics" website="fr" locale="fr_FR">
            <criteria type="and">
                <attribute name="stock_qty" is="GreaterThan">0</attribute>
                <attribute name="brand" is="Equal">Asics</attribute>
            </criteria>
        </listing>
    </listings>
</catalog>

=== Flagbit/catalog/tests/shared-fixture/configurable_product_adipure.xml
<?xml version="1.0"?>
<catalog xmlns="http://lizardsandpumpkins.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://lizardsandpumpkins.com ../../schema/catalog.xsd">
    <products>
        <product type="configurable" sku="M29540" tax_class="19%">
            <images>
                <image>
                    <file>m29540_standardview.jpg</file>
                    <label locale="de_DE">Das Hauptbild</label>
                    <label locale="en_US">The main image label for this shoe</label>
                </image>
                <image>
                    <file>m29540_backview.jpg</file>
                    <label>Yet another image label</label>
                </image>
            </images>
            <attributes>
                <attribute name="url_key">adipure-360</attribute>
                <attribute name="category">sale</attribute>
                <attribute name="category">men-running-shoes</attribute>
                <attribute name="category">specials</attribute>
                <attribute name="stock_qty">5</attribute>
                <attribute name="backorders">true</attribute>
                <attribute name="name">Adipure 360.2 Prima</attribute>
                <attribute name="price">89.95</attribute>
                <attribute name="special_price">44.97</attribute>
                <attribute name="description"><![CDATA[Adidas adiPure 360.2 Prima<br><br>
- Flex Grooves: Flexibilität für ein natürliches Laufgefühl.<br>
- Atmungsaktives Mesh: Ermöglicht Luftzirkulation, die für ein angenehmes Gefühl am Fuß sorgt<br>
- Die All-Over-Graphik Ausführung  des Schuhs gibt dir einen einzigartigen Look<br><br>
TEXTILE/SYNTHETICS]]></attribute>
                <attribute name="brand">Adidas</attribute>
                <attribute name="style">Natural-Running (Free)</attribute>
                <attribute name="gender">Damen</attribute>
                <attribute name="series">Adipure</attribute>
            </attributes>
            <variations>
                <attribute>color</attribute>
                <attribute>size</attribute>
            </variations>
            <associated_products>
                <product sku="218765-333-1" type="simple" tax_class="19%">
                    <attributes>
                        <attribute name="stock_qty">6</attribute>
                        <attribute name="backorders">false</attribute>
                        <attribute name="color" locale="en_US">Red</attribute>
                        <attribute name="color" locale="de_DE">Rot</attribute>
                        <attribute name="color" locale="fr_FR">Rouge</attribute>
                        <attribute name="size">12.5</attribute>
                        <attribute name="size_eu">47</attribute>
                    </attributes>
                </product>
                <product sku="218765-333-2" type="simple" tax_class="19%">
                    <attributes>
                        <attribute name="stock_qty">0</attribute>
                        <attribute name="backorders">false</attribute>
                        <attribute name="color" locale="en_US">Red</attribute>
                        <attribute name="color" locale="de_DE">Rot</attribute>
                        <attribute name="color" locale="fr_FR">Rouge</attribute>
                        <attribute name="size">12</attribute>
                        <attribute name="size_eu">46</attribute>
                    </attributes>
                </product>
                <product sku="218765-333-3" type="simple" tax_class="19%">
                    <attributes>
                        <attribute name="stock_qty">45</attribute>
                        <attribute name="backorders">false</attribute>
                        <attribute name="color" locale="en_US">Red</attribute>
                        <attribute name="color" locale="de_DE">Rot</attribute>
                        <attribute name="color" locale="fr_FR">Rouge</attribute>
                        <attribute name="size">11.5</attribute>
                        <attribute name="size_eu">45</attribute>
                    </attributes>
                </product>
                <product sku="218765-333-4" type="simple" tax_class="19%">
                    <attributes>
                        <attribute name="stock_qty">5</attribute>
                        <attribute name="backorders">false</attribute>
                        <attribute name="color" locale="en_US">Red</attribute>
                        <attribute name="color" locale="de_DE">Rot</attribute>
                        <attribute name="color" locale="fr_FR">Rouge</attribute>
                        <attribute name="size">10</attribute>
                        <attribute name="size_eu">43</attribute>
                    </attributes>
                </product>
                <product sku="218765-333-6" type="simple" tax_class="19%">
                    <attributes>
                        <attribute name="stock_qty">0</attribute>
                        <attribute name="backorders">true</attribute>
                        <attribute name="color" locale="en_US">Blue</attribute>
                        <attribute name="color" locale="de_DE">Blau</attribute>
                        <attribute name="color" locale="fr_FR">Bleu</attribute>
                        <attribute name="size">12</attribute>
                        <attribute name="size_eu">46</attribute>
                    </attributes>
                </product>
                <product sku="218765-333-7" type="simple" tax_class="19%">
                    <attributes>
                        <attribute name="stock_qty">5</attribute>
                        <attribute name="backorders">false</attribute>
                        <attribute name="color" locale="en_US">Blue</attribute>
                        <attribute name="color" locale="de_DE">Blau</attribute>
                        <attribute name="color" locale="fr_FR">Bleu</attribute>
                        <attribute name="size">11.5</attribute>
                        <attribute name="size_eu">45</attribute>
                    </attributes>
                </product>
            </associated_products>
        </product>
    </products>
</catalog>
