=== Flagbit/catalog/schema/snippet.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://lizardsandpumpkins.com"
        xmlns="http://lizardsandpumpkins.com"
        elementFormDefault="qualified">
    <xs:element name="snippet">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="block" type="block" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="block">
        <xs:sequence>
            <xs:element name="block" type="block" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="class" type="xs:string" use="required" />
        <xs:attribute name="template" type="xs:string" use="required" />
    </xs:complexType>
</xs:schema>

=== Flagbit/catalog/theme/layout/product_listing.xml
<?xml version="1.0"?>
<snippet xmlns="http://lizardsandpumpkins.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://lizardsandpumpkins.com ../../schema/snippet.xsd">
    <block name="product_details_snippet" class="LizardsAndPumpkins\Renderer\Block" template="template/2columns-left.phtml">
        <block name="head" class="LizardsAndPumpkins\Renderer\Block" template="template/head.phtml" />
        <block name="header" class="LizardsAndPumpkins\Renderer\Block" template="template/header.phtml">
            <block name="ekomi" class="LizardsAndPumpkins\Renderer\Block" template="template/ekomi.phtml" />
        </block>
        <block name="left" class="LizardsAndPumpkins\Renderer\Block" template="template/left.phtml" />
        <block name="content" class="LizardsAndPumpkins\Renderer\Block" template="template/list.phtml" />
        <block name="footer" class="LizardsAndPumpkins\Renderer\Block" template="template/footer.phtml" />
    </block>
</snippet>
