=== Flagbit/catalog/data/product.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://brera.io"
        xmlns="http://brera.io"
        elementFormDefault="qualified">
    <xs:element name="products">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="product" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="abstractProduct">
                                <xs:sequence>
                                    <xs:element name="url_key" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="xs:string">
                                                    <xs:attribute name="lang" type="xs:string" />
                                                </xs:extension>
                                            </xs:simpleContent>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="categories" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="category" type="xs:string" maxOccurs="unbounded" />
                                            </xs:sequence>
                                            <xs:attribute name="website" type="xs:string" />
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="tax_class_ids">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="tax_class_id" type="xs:positiveInteger" maxOccurs="unbounded" />
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="assets">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="image" maxOccurs="unbounded">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="file" maxOccurs="unbounded">
                                                                <xs:complexType>
                                                                    <xs:simpleContent>
                                                                        <xs:extension base="xs:string">
                                                                            <xs:attribute name="lang" type="xs:string" />
                                                                        </xs:extension>
                                                                    </xs:simpleContent>
                                                                </xs:complexType>
                                                            </xs:element>
                                                            <xs:element name="label" maxOccurs="unbounded">
                                                                <xs:complexType>
                                                                    <xs:simpleContent>
                                                                        <xs:extension base="xs:string">
                                                                            <xs:attribute name="lang" type="xs:string" />
                                                                        </xs:extension>
                                                                    </xs:simpleContent>
                                                                </xs:complexType>
                                                            </xs:element>
                                                        </xs:sequence>
                                                        <xs:attribute name="identifier" type="xs:string" />
                                                        <xs:attribute name="gallery" type="xs:boolean" />
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="pdf" maxOccurs="unbounded" minOccurs="0">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="file" maxOccurs="unbounded">
                                                                <xs:complexType>
                                                                    <xs:simpleContent>
                                                                        <xs:extension base="xs:string">
                                                                            <xs:attribute name="lang" type="xs:string" />
                                                                        </xs:extension>
                                                                    </xs:simpleContent>
                                                                </xs:complexType>
                                                            </xs:element>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="associated_products" minOccurs="0">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="product" type="abstractProduct" maxOccurs="unbounded" />
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="type" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="simple" />
                                            <xs:enumeration value="configurable" />
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <!-- The line below most likely won't. Need XSD 1.1 compliant parser to test. -->
                                <xs:assert test="if(@type eq 'configurable') then associated_products
                                     else not(associated_products)" />
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="abstractProduct">
        <xs:all>
            <xs:element name="inventory" minOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="qty" type="xs:nonNegativeInteger" default="0" minOccurs="0" />
                        <xs:element name="is_in_stock" type="xs:boolean" />
                        <xs:element name="backorders" type="xs:boolean" default="false" minOccurs="0" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="attributes">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="attribute" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="label" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="xs:string">
                                                    <xs:anyAttribute processContents="skip" />
                                                </xs:extension>
                                            </xs:simpleContent>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="code" type="xs:string" use="required" />
                                <xs:anyAttribute processContents="skip" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="sku" type="xs:string" use="required" />
        <xs:attribute name="visible" type="xs:boolean" use="required" />
    </xs:complexType>

    <xs:simpleType name="positiveDecimal">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Flagbit/catalog/tests/shared-fixture/product.xml
<?xml version="1.0"?>
<products xmlns="http://brera.io" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://brera.io ../../data/product.xsd">
    <product type="simple" sku="118235-251" visible="true" tax_class_id="5">
        <assets>
            <image identifier="main">
                <file>products/118235/118235-251.1.png</file>
                <label>The main image label</label>
            </image>
            <image identifier="small" gallery="false">
                <file>products/118235/118235-251.2.png</file>
                <label lang="de_DE">Der Text zum zweiten Bild</label>
                <label lang="en_US">A secondary image label</label>
            </image>
            <image>
                <file lang="de_DE">products/118235/118235-251.2de.png</file>
                <file lang="de_US">products/118235/118235-251.2us.png</file>
                <label>A secondary image label</label>
            </image>
        </assets>
        <attributes>
            <attribute code="category" website="ru_de">men</attribute>
            <attribute code="category" website="ru_de">women</attribute>
            <attribute code="category" website="ru_de">men-accessories</attribute>
            <attribute code="category" website="ru_de">women-accessories</attribute>
            <attribute code="category" website="ru_en">men-accessories</attribute>
            <attribute code="category" website="ru_en">women-accessories</attribute>
            <attribute code="stock_qty">5</attribute>
            <attribute code="backorders">true</attribute>
            <attribute code="url_key" lang="de_DE">led-arm-signallampe</attribute>
            <attribute code="url_key" lang="en_US">led-armflasher</attribute>
            <attribute code="name" lang="de_DE">LED Arm-Signallampe</attribute>
            <attribute code="name" lang="en_US">LED Armflasher</attribute>
            <attribute code="price" customer_group="retail" website="ru_de">12.95</attribute>
            <attribute code="price" website="ru_en">11.45</attribute>
            <attribute code="special_price" website="ru_de">11.95</attribute>
            <attribute code="image_main">main</attribute>
            <attribute code="image_listing">main</attribute>
            <attribute code="image_thumbnail">small</attribute>
            <attribute code="weight">11.2</attribute>
            <attribute code="short_description" lang="de_DE"><![CDATA[Pro Touch LED Armflasher<br />&#13;
<br />&#13;
LED Armflasher mit elastischem Band und Flasher mit variabler Blinkfolge,&#13;
Flasher abnehmbar.&#13;]]></attribute>
            <attribute code="short_description" lang="en_US"><![CDATA[Pro Touch LED Armflasher<br />&#13;
<br />&#13;
LED Armflasher with elastic Band and Flasher&#13;]]></attribute>
        </attributes>
    </product>

    <product type="configurable" sku="218765-333" visible="true" tax_class_id="5">
        <assets>
            <image identifier="main-shoe-picture">
                <file>products/218765/218765-333.1.png</file>
                <label lang="de_DE">Das Hauptbild</label>
                <label lang="en_US">The main image label for this shoe</label>
            </image>
            <image identifier="drawing">
                <file lang="de_DE">products/218765/218765-333.2de.png</file>
                <file lang="en_US">products/218765/218765-333.2en.png</file>
                <label>Der Text zum zweiten Bild</label>
            </image>
            <image identifier="small">
                <file>products/218765/218765-333.3.png</file>
                <label>Yet another image label</label>
            </image>
            <pdf>
                <file>guarantee-document.pdf</file>
            </pdf>
        </assets>
        <attributes>
            <attribute code="url_key">adipure-360</attribute>
            <attribute code="category">men-running-shoes</attribute>
            <attribute code="category">specials</attribute>
            <attribute code="stock_qty">5</attribute>
            <attribute code="backorders">true</attribute>
            <attribute code="name">adiPure 360</attribute>
            <attribute code="price">12.95</attribute>
            <attribute code="image_main">main-shoe-picture</attribute>
            <attribute code="image_listing">small</attribute>
            <attribute code="image_thumbnail">small</attribute>
            <attribute code="short_description"><![CDATA[<div>Adidas adiPure 360</div>

<li>Techfit bietet Unterstützung in den wichtigen Bereichen.</li>
<li>Technisierte Maschen: Die ungleichmäßige Maschenstruktur vereint dichte und offene Maschen.</li>
<li>Flex Grooves: Flexibilität für ein natürliches Laufgefühl.</li>
<li>Nahtloses textiles und Hightech-Obermaterial aus Mesh</li>
<li>Dichteres und offeneres Mesh-Muster für Stützung und Atmungsaktivität, wo es gebraucht wird.</li>
<li>Komfortables Synthetikfutter</li>
<li>Ultraweiches, wasserfestes SUPERCLOUD EVA-Fußbett für schnelltrocknenden Komfort</li>
<li>Flex-Rillen für einen angenehmen und natürlichen Lauf</li>
<li>ABRIEBFESTE Gummiaußensohle</li>
]]></attribute>
        </attributes>
        <associated_products>
            <product sku="218765-333-1" visible="false" tax_class_id="5">
                <attributes>
                    <attribute code="stock_qty">5</attribute>
                    <attribute code="color">
                        <label lang="en_US">Red</label>
                        <label lang="de_DE">Rot</label>
                    </attribute>
                    <attribute code="size">
                        <label>US 12.5 - EU 47</label>
                    </attribute>
                </attributes>
            </product>
            <product sku="218765-333-2" visible="false" tax_class_id="5">
                <attributes>
                    <attribute code="stock_qty">750</attribute>
                    <attribute code="color">
                        <label lang="en_US">Red</label>
                        <label lang="de_DE">Rot</label>
                    </attribute>
                    <attribute code="size">
                        <label>US 12 - EU 46</label>
                    </attribute>
                </attributes>
            </product>
            <product sku="218765-333-3" visible="false" tax_class_id="5">
                <attributes>
                    <attribute code="stock_qty">45</attribute>
                    <attribute code="color">
                        <label lang="en_US">Red</label>
                        <label lang="de_DE">Rot</label>
                    </attribute>
                    <attribute code="size">
                        <label>US 11.5 - EU 45</label>
                    </attribute>
                </attributes>
            </product>
            <product sku="218765-333-4" visible="false" tax_class_id="5">
                <attributes>
                    <attribute code="stock_qty">5</attribute>
                    <attribute code="color">
                        <label lang="en_US">Red</label>
                        <label lang="de_DE">Rot</label>
                    </attribute>
                    <attribute code="size">
                        <label>US 10 - EU 43</label>
                    </attribute>
                </attributes>
            </product>
            <product sku="218765-333-5" visible="false" tax_class_id="5">
                <attributes>
                    <attribute code="stock_qty">5</attribute>
                    <attribute code="color">
                        <label lang="en_US">Blue</label>
                        <label lang="de_DE">Blau</label>
                    </attribute>
                    <attribute code="size">
                        <label>US 12.5 - EU 47</label>
                    </attribute>
                </attributes>
            </product>
            <product sku="218765-333-6" visible="false" tax_class_id="5">
                <attributes>
                    <attribute code="stock_qty">5</attribute>
                    <attribute code="color">
                        <label lang="en_US">Blue</label>
                        <label lang="de_DE">Blau</label>
                    </attribute>
                    <attribute code="size">
                        <label>US 12 - EU 46</label>
                    </attribute>
                </attributes>
            </product>
            <product sku="218765-333-7" visible="false" tax_class_id="5">
                <attributes>
                    <attribute code="stock_qty">5</attribute>
                    <attribute code="color">
                        <label lang="en_US">Blue</label>
                        <label lang="de_DE">Blau</label>
                    </attribute>
                    <attribute code="size">
                        <label>US 11.5 - EU 45</label>
                    </attribute>
                </attributes>
            </product>
        </associated_products>
    </product>
</products>
